### ISSUE TITLE
개발자 램프업

### ISSUE THREAD

**Issue by ym1085** [ym1085/TIL#30]
# 램프업
## 🏆 Goal : 프로세스 - 해당 서비스를 빠르게 파악하기 위한 전략
- [`백기선님 개발자 고민 상담`](https://www.youtube.com/watch?v=a3VV46wUKto)
- 더 큰 책임이 누군가에게 있는가?
- 어떤 자세와 생각을 가지고 업무에 진행 할것인가?

### 멘티 : 멘토 = 5 : 5
`정해진 기간이 있었고, 목표를 달성하지 못했다면 일단 우리의 잘못이다, 우리는 프로이기에`
1. 해당 프로세스를 파악하기 위해 사수의 도움을 받아야한다?
2. `사수`를 옆에 또는 `사수 옆자리`에 가서 같이 소스를 파악하는게 가장 빠르다
3. 문서, 코드.. 등을 혼자 보는게 살짝 도움은 되겠지만 `속도`가 뎌디다
4. 전체 그림을 이해해야 하는데, 확실한 개념이 잡히지 않으면 이해가 될 때까지 피드백 요청
    - 막연하게 피드백 요청하는게 아니고, `문제 상황` - `진행 상황` 정리 후 피드백 요청

### 업무에 빠르게 적응하는 방법
`신입이거나, 다른 팀으로 옮겨가는 경우 무조건 사수와 미팅을 잡는다`
- `목표` 및 `스코프` 설정
  - 어느정도 기간동안 해당 시스템 플랫폼에 대해 어느정도의 이해를 가져와야 하는가? 
  - 사수도 나도 같은 생각을 하고 있어야 한다.
    - On the same page
1. `혼자 한번 본다`
    - `좋은 예`: 감이 안 오면 바로 미팅을 잡거나, 사수에게 피드백을 요청한다
    - `안좋은 예`: 혼자서 이상한 방향성으로 진행을 하고 나중에 사수에게 리뷰 요청 시 폭망
2. `사수`가 비협조적으로 나올 경우 매니저에게 요청을 한다, 매니저 없을 시 상급자에게 요청
3. `중요`: 모르는 부분이 있을 경우 빠르게 래퍼런스를 참조한 후에 참조 자료가 없거나 시간이 
생각보다 오래 걸린다면, 30분 ~ 1시간 정도만 고민한 후 아래 상황을 정리하여 피드백 요청
- 문제 상황 정리
- 문제 해결을 위해 어떤 부분을 참고 하였으며 현재 상태 공유
- 피드백을 받는다
- 문제 해결 시도
  - 문제가 해결이 된 경우 감사 표시
  - 문제가 해결이 안 된 경우 한번 더 고민 후 피드백 요청
    - 문제 해결

**Comment by youngsikwon** [comment]
ym1085님은 어떤 방향성으로 문제 해결을 하시나요?
